#!/bin/sh
# File generated by ocamlbuild

cd /mnt/c/Users/yassi/OneDrive/universite-paris-saclay/semestre-trois/programmation-fonctionelle/projet-yassine-lounes-ipf

rm -f grid.cmi
rm -f grid.cmo
rm -f maze.cmi
rm -f maze.cmo
# Also clean the script itself
rm -f /mnt/c/Users/yassi/OneDrive/universite-paris-saclay/semestre-trois/programmation-fonctionelle/projet-yassine-lounes-ipf/_build/sanitize.sh
